=== Fiser04/Fiser-obsidian/3.1/Znacky/ukol1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Faktury (Faktura*)>
<!ELEMENT Faktura (Dodavatel, Odběratel, Polozky, Souhrn)>
<!ATTLIST Faktura id CDATA #IMPLIED>

<!ELEMENT Dodavatel (Nazev, Adresa, Telefon, ICO, DIC)>
<!ELEMENT Odběratel (Nazev, Adresa, Telefon)>
<!ELEMENT Polozky (Polozka*)>
<!ELEMENT Polozka (Nazev, Mnozstvi, CenaJednotkova, CenaJednotkovaDPH, CenaCelkem, CenaCelkemDPH)>
<!ELEMENT Souhrn (Castka, CenaCelkemDPH)>
<!ELEMENT Castka (#PCDATA)>

<!ELEMENT Nazev (#PCDATA)>
<!ELEMENT Adresa (#PCDATA)>
<!ELEMENT Telefon (#PCDATA)>
<!ELEMENT ICO (#PCDATA)>
<!ELEMENT DIC (#PCDATA)>
<!ELEMENT Mnozstvi (#PCDATA)>
<!ELEMENT CenaJednotkova (#PCDATA)>
<!ELEMENT CenaJednotkovaDPH (#PCDATA)>
<!ELEMENT CenaCelkem (#PCDATA)>
<!ELEMENT CenaCelkemDPH (#PCDATA)>
<!ATTLIST Castka Mena (CZK|EURO) #REQUIRED>

=== Fiser04/Fiser-obsidian/3.1/Znacky/ukol1-generated.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Faktury SYSTEM "ukol1.dtd">
<Faktury>
    <Faktura id="1">
        <Dodavatel>
            <Nazev>NotebookShop s.r.o.</Nazev>
            <Adresa>Technická 10, 602 00 Brno</Adresa>
            <Telefon>+420515123456</Telefon>
            <ICO>87654321</ICO>
            <DIC>CZ87654321</DIC>
        </Dodavatel>
        <Odběratel>
            <Nazev>Jan Novák</Nazev>
            <Adresa>Sluneční 12, Praha 3</Adresa>
            <Telefon>+420601234567</Telefon>
        </Odběratel>
        <Polozky>
            <Polozka>
                <Nazev>Notebook Apple MacBook Air 13 M3</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>32990</CenaJednotkova>
                <CenaJednotkovaDPH>39917.9</CenaJednotkovaDPH>
                <CenaCelkem>32990</CenaCelkem>
                <CenaCelkemDPH>39917.9</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook Lenovo ThinkPad E16</Nazev>
                <Mnozstvi>3</Mnozstvi>
                <CenaJednotkova>18490</CenaJednotkova>
                <CenaJednotkovaDPH>22372.9</CenaJednotkovaDPH>
                <CenaCelkem>55470</CenaCelkem>
                <CenaCelkemDPH>67118.7</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook HP ProBook 450</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>21990</CenaJednotkova>
                <CenaJednotkovaDPH>26607.9</CenaJednotkovaDPH>
                <CenaCelkem>21990</CenaCelkem>
                <CenaCelkemDPH>26607.9</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>RAM 16GB DDR5</Nazev>
                <Mnozstvi>3</Mnozstvi>
                <CenaJednotkova>1890</CenaJednotkova>
                <CenaJednotkovaDPH>2286.9</CenaJednotkovaDPH>
                <CenaCelkem>5670</CenaCelkem>
                <CenaCelkemDPH>6860.7</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Klávesnice mechanická</Nazev>
                <Mnozstvi>3</Mnozstvi>
                <CenaJednotkova>1990</CenaJednotkova>
                <CenaJednotkovaDPH>2407.9</CenaJednotkovaDPH>
                <CenaCelkem>5970</CenaCelkem>
                <CenaCelkemDPH>7223.7</CenaCelkemDPH>
            </Polozka>
        </Polozky>
        <Souhrn>
            <Castka Mena="CZK">122090</Castka>
            <CenaCelkemDPH>147728.9</CenaCelkemDPH>
        </Souhrn>
    </Faktura>
    <Faktura id="2">
        <Dodavatel>
            <Nazev>NotebookShop s.r.o.</Nazev>
            <Adresa>Technická 10, 602 00 Brno</Adresa>
            <Telefon>+420515123456</Telefon>
            <ICO>87654321</ICO>
            <DIC>CZ87654321</DIC>
        </Dodavatel>
        <Odběratel>
            <Nazev>Petra Svobodová</Nazev>
            <Adresa>Lipová 45, Brno</Adresa>
            <Telefon>+420602345678</Telefon>
        </Odběratel>
        <Polozky>
            <Polozka>
                <Nazev>RAM 16GB DDR5</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>1890</CenaJednotkova>
                <CenaJednotkovaDPH>2286.9</CenaJednotkovaDPH>
                <CenaCelkem>1890</CenaCelkem>
                <CenaCelkemDPH>2286.9</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook Dell Inspiron 14</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>17490</CenaJednotkova>
                <CenaJednotkovaDPH>21162.9</CenaJednotkovaDPH>
                <CenaCelkem>17490</CenaCelkem>
                <CenaCelkemDPH>21162.9</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Monitor 27" IPS</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>6990</CenaJednotkova>
                <CenaJednotkovaDPH>8457.9</CenaJednotkovaDPH>
                <CenaCelkem>6990</CenaCelkem>
                <CenaCelkemDPH>8457.9</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook Lenovo ThinkPad E16</Nazev>
                <Mnozstvi>3</Mnozstvi>
                <CenaJednotkova>18490</CenaJednotkova>
                <CenaJednotkovaDPH>22372.9</CenaJednotkovaDPH>
                <CenaCelkem>55470</CenaCelkem>
                <CenaCelkemDPH>67118.7</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Klávesnice mechanická</Nazev>
                <Mnozstvi>3</Mnozstvi>
                <CenaJednotkova>1990</CenaJednotkova>
                <CenaJednotkovaDPH>2407.9</CenaJednotkovaDPH>
                <CenaCelkem>5970</CenaCelkem>
                <CenaCelkemDPH>7223.7</CenaCelkemDPH>
            </Polozka>
        </Polozky>
        <Souhrn>
            <Castka Mena="CZK">87810</Castka>
            <CenaCelkemDPH>106250.1</CenaCelkemDPH>
        </Souhrn>
    </Faktura>
    <Faktura id="3">
        <Dodavatel>
            <Nazev>NotebookShop s.r.o.</Nazev>
            <Adresa>Technická 10, 602 00 Brno</Adresa>
            <Telefon>+420515123456</Telefon>
            <ICO>87654321</ICO>
            <DIC>CZ87654321</DIC>
        </Dodavatel>
        <Odběratel>
            <Nazev>Martin Dvořák</Nazev>
            <Adresa>Třída Míru 8, Ostrava</Adresa>
            <Telefon>+420603456789</Telefon>
        </Odběratel>
        <Polozky>
            <Polozka>
                <Nazev>Notebook Lenovo ThinkPad E16</Nazev>
                <Mnozstvi>3</Mnozstvi>
                <CenaJednotkova>18490</CenaJednotkova>
                <CenaJednotkovaDPH>22372.9</CenaJednotkovaDPH>
                <CenaCelkem>55470</CenaCelkem>
                <CenaCelkemDPH>67118.7</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook MSI Modern 15</Nazev>
                <Mnozstvi>2</Mnozstvi>
                <CenaJednotkova>14490</CenaJednotkova>
                <CenaJednotkovaDPH>17532.9</CenaJednotkovaDPH>
                <CenaCelkem>28980</CenaCelkem>
                <CenaCelkemDPH>35065.8</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Monitor 27" IPS</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>6990</CenaJednotkova>
                <CenaJednotkovaDPH>8457.9</CenaJednotkovaDPH>
                <CenaCelkem>6990</CenaCelkem>
                <CenaCelkemDPH>8457.9</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook Apple MacBook Air 13 M3</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>32990</CenaJednotkova>
                <CenaJednotkovaDPH>39917.9</CenaJednotkovaDPH>
                <CenaCelkem>32990</CenaCelkem>
                <CenaCelkemDPH>39917.9</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook Lenovo IdeaPad Slim 3</Nazev>
                <Mnozstvi>3</Mnozstvi>
                <CenaJednotkova>11490</CenaJednotkova>
                <CenaJednotkovaDPH>13902.9</CenaJednotkovaDPH>
                <CenaCelkem>34470</CenaCelkem>
                <CenaCelkemDPH>41708.7</CenaCelkemDPH>
            </Polozka>
        </Polozky>
        <Souhrn>
            <Castka Mena="CZK">158900</Castka>
            <CenaCelkemDPH>192269</CenaCelkemDPH>
        </Souhrn>
    </Faktura>
    <Faktura id="4">
        <Dodavatel>
            <Nazev>NotebookShop s.r.o.</Nazev>
            <Adresa>Technická 10, 602 00 Brno</Adresa>
            <Telefon>+420515123456</Telefon>
            <ICO>87654321</ICO>
            <DIC>CZ87654321</DIC>
        </Dodavatel>
        <Odběratel>
            <Nazev>Lenka Černá</Nazev>
            <Adresa>Nádražní 22, Plzeň</Adresa>
            <Telefon>+420604567890</Telefon>
        </Odběratel>
        <Polozky>
            <Polozka>
                <Nazev>Monitor 27" IPS</Nazev>
                <Mnozstvi>2</Mnozstvi>
                <CenaJednotkova>6990</CenaJednotkova>
                <CenaJednotkovaDPH>8457.9</CenaJednotkovaDPH>
                <CenaCelkem>13980</CenaCelkem>
                <CenaCelkemDPH>16915.8</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Myš Logitech MX Master 3S</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>2490</CenaJednotkova>
                <CenaJednotkovaDPH>3012.9</CenaJednotkovaDPH>
                <CenaCelkem>2490</CenaCelkem>
                <CenaCelkemDPH>3012.9</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook HP ProBook 450</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>21990</CenaJednotkova>
                <CenaJednotkovaDPH>26607.9</CenaJednotkovaDPH>
                <CenaCelkem>21990</CenaCelkem>
                <CenaCelkemDPH>26607.9</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook Dell Inspiron 14</Nazev>
                <Mnozstvi>2</Mnozstvi>
                <CenaJednotkova>17490</CenaJednotkova>
                <CenaJednotkovaDPH>21162.9</CenaJednotkovaDPH>
                <CenaCelkem>34980</CenaCelkem>
                <CenaCelkemDPH>42325.8</CenaCelkemDPH>
            </Polozka>
            <Polozka>
                <Nazev>Notebook Apple MacBook Air 13 M3</Nazev>
                <Mnozstvi>1</Mnozstvi>
                <CenaJednotkova>32990</CenaJednotkova>
                <CenaJednotkovaDPH>39917.9</CenaJednotkovaDPH>
                <CenaCelkem>32990</CenaCelkem>
                <CenaCelkemDPH>39917.9</CenaCelkemDPH>
            </Polozka>
        </Polozky>
        <Souhrn>
            <Castka Mena="CZK">106430</Castka>
            <CenaCelkemDPH>128780.3</CenaCelkemDPH>
        </Souhrn>
    </Faktura>
    <Faktura id="5">
        <Dodavatel>
            <Nazev>NotebookShop s.r.o.</Nazev>
            <Adresa>Technická 10, 602 00 Brno</Adresa>
            <Telefon>+420515123456</Telefon>
