=== Fiser04/Fiser-obsidian/3.1/Znacky/zamestnanci.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="zamestnanci.xsd"
	xmlns="zamestnanci.xsd"
	elementFormDefault="qualified">

	<xs:simpleType name="platType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="200000"/>
			<xs:fractionDigits value="2"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="pscType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{3} ?\d{2}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="oddeleniType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="IT"></xs:enumeration>
			<xs:enumeration value="HR"></xs:enumeration>
			<xs:enumeration value="OBCHOD"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="zamestnanci">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="zamestnanec" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="jmeno" type="xs:string"/>
							<xs:element name="prijmeni" type="xs:string"/>
							<xs:element name="plat">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="platType">
											<xs:attribute name="mena" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="narozeni" type="xs:date"/>
							<xs:element name="psc" type="pscType"/>
							<xs:element name="oddeleni" type="oddeleniType"/>
							<xs:element name="kontakt">
								<xs:complexType>
									<xs:choice>
										<xs:element name="email" type="xs:string"/>
										<xs:element name="telefon" type="xs:string"/>
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Fiser04/Fiser-obsidian/3.1/Znacky/zamestnanci.xml
<?xml version="1.0" encoding="UTF-8"?>
<zamestnanci xmlns="zamestnanci.xsd"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="zamestnanci.xsd zamestnanci.xsd">
    <zamestnanec id="1">
        <jmeno>Jan</jmeno>
        <prijmeni>Novák</prijmeni>
        <plat mena="CZK">45000.00</plat>
        <narozeni>1990-05-14</narozeni>
        <psc>110 00</psc>
        <oddeleni>IT</oddeleni>
        <kontakt>
            <email>jan.novak@example.cz</email>
            <telefon>+420 777 123 450</telefon>
        </kontakt>
    </zamestnanec>
    <zamestnanec id="2">
        <jmeno>Ondra</jmeno>
        <prijmeni>Triska</prijmeni>
        <plat mena="CZK">40000.00</plat>
        <narozeni>1983-01-15</narozeni>
        <psc>110 00</psc>
        <oddeleni>OBCHOD</oddeleni>
        <kontakt>
            <telefon>+420 777 123 111</telefon>
        </kontakt>
    </zamestnanec>
</zamestnanci>
